# PowerShell script to fix dependency conflicts and run the project

# Check Node.js version
Write-Host "Checking Node.js version..."
$nodeVersion = node -v
Write-Host "Current Node.js version: $nodeVersion"
if ($nodeVersion -lt "v18.0.0") {
    Write-Warning "Please upgrade Node.js to version 18 or higher manually before running this script."
    exit 1
}

# Remove node_modules and lock files in root, client, and server
Write-Host "Removing node_modules and lock files..."
Remove-Item -Recurse -Force -ErrorAction SilentlyContinue node_modules, package-lock.json, yarn.lock
Remove-Item -Recurse -Force -ErrorAction SilentlyContinue client\node_modules, client\package-lock.json, client\yarn.lock
Remove-Item -Recurse -Force -ErrorAction SilentlyContinue server\node_modules, server\package-lock.json, server\yarn.lock

# Install root dependencies
Write-Host "Installing root dependencies..."
npm install

# Fix client dependencies
Write-Host "Fixing client dependencies..."
Set-Location client
npm install react@18.2.0 react-dom@18.2.0 next@13.4.4
npm install @mui/material@5.13.7 @emotion/react@11.11.1 @emotion/styled@11.11.0
npm install @mui/icons-material@5.11.16
npm install @mui/lab@5.0.0-alpha.125
npm install @mui/x-data-grid@6.15.0
npm install @mui/x-date-pickers@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6.7.0
npm install @mui/x-date-pickers-pro@6
